name: GoRest API Tests - UAT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # allows manual trigger from GitHub UI
    inputs:
        environment:
            description: 'Select environment to run tests against'
            required: true
            default: 'uat'
            type: choice
            options:
              - uat
              - preprod

# required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
     FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Set environment
        run: |
         echo "ENV_NAME=${{ inputs.environment || 'uat' }}" >> $GITHUB_ENV

      - name: Set API token
        run: |
          if [ "$ENV_NAME" = "uat" ]; then
            echo "API_TOKEN=${{ secrets.API_TOKEN_UAT }}" >> $GITHUB_ENV
          else
            echo "API_TOKEN=${{ secrets.API_TOKEN_PRE }}" >> $GITHUB_ENV
          fi

      - name: Create env file
        run: |
          mkdir -p environments
          echo "BASE_URL=${{ vars.BASE_URL }}" >> environments/.env.$ENV_NAME
          echo "API_TOKEN=$API_TOKEN" >> environments/.env.$ENV_NAME

      - name: Run API tests
        run: ENV=$ENV_NAME npx playwright test scripts/CapstoneProjects/GoRestAPI/users.spec.ts

      - name: Generate Allure report
        if: always()
        run: npx allure generate allure-results -o allure-report --clean
        env:
          ALLURE_ENVIRONMENT: $ENV_NAME

      - name: Upload HTML report - ${{ env.ENV_NAME }}
        uses: actions/upload-artifact@v4
        if: always() # upload even if tests fail
        with:
          name: playwright-report-${{ env.ENV_NAME }}
          path: playwright-report/
          retention-days: 20
    
      - name: Upload XML report - ${{ env.ENV_NAME }}
        uses: actions/upload-artifact@v4
        if: always() # upload even if tests fail
        with:
            name: junit-report-${{ env.ENV_NAME }}
            path: test-results.xml
            retention-days: 20
      
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        if: always()

      - name: Upload Allure report to Pages
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: allure-report/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4